apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
spec:
  replicas: 2 # Adjust as needed
  selector: 
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
      - name: my-node-app
        # image: gcr.io/your-project-id/your-app-image # Replace with your image
        ports:
        - containerPort: 3000
